added hints on limitations around ES with small memory
camunda/camunda-platform-docs pull request #1000
Opened 2022-06-29 10:51 UTC by berndruecker

Changes required after discussion with @romansmirnov around latest performance observations

2022-06-29 10:52 UTC, berndruecker commented
@romansmirnov WDYT - would that change cut it? 
I work on the sales docs in parallel and make sure they are in-sync...

2022-07-07 08:18 UTC, romansmirnov commented on docs/components/best-practices/architecture/sizing-your-environment.md
> +s you can see in the table above, such a cluster can serve 500,000 process instances / day and store up to 100 thousand process instances (in-flight and history). You might wonder, why the total numb
```suggestion
As you can see in the table above, such a cluster can serve 500,000 process instances / day and store up to 100 thousand process instances (in-flight and history). You might wonder, why the total number of process instances stored is that low. This is related to limited resources provided to ElasticSearch, yielding in performance problems with too many data stored there. By increasing the available memory to ElasticSearch you can also increase that number. At the same time, even with this rather low number, you can always gurantee the throughput of the core workflow engine during peak loads, as this perfomance is not influenced. Also, you can always increase memory for ElasticSearch later on when if it is required.
```

2022-07-07 22:02 UTC, christinaausley requested changes
A few commits with some style guide fixes and a few comments for clarification. Once resolved feel free to re-request review and I'll approve and merge.

2022-07-11 10:19 UTC, berndruecker commented on docs/components/best-practices/architecture/sizing-your-environment.md
> +Provisioning Camunda Platform 8 onto your self-managed Kubernetes cluster might depend on various factors. For example, most customes already have own teams providing Elasticsearch for them as a serv
Now - "the following example" is referring to the table that comes next

2022-07-12 14:20 UTC, akeller commented
@christinaausley are you still waiting for feedback from @berndruecker or @romansmirnov on this PR?

2022-07-12 18:04 UTC, christinaausley commented on docs/components/best-practices/architecture/sizing-your-environment.md
> +Elasticsearch needs enough memory available to load a big chunk of this data into memory.
@berndruecker Double checking on this comment -- then we should be good to merge.

2022-07-13 15:05 UTC, akeller approved these changes

2022-07-13 15:05 UTC, merged