rename connectors guide
camunda/camunda-platform-docs pull request #1206
Opened 2022-08-29 22:17 UTC by christinaausley

## What is the purpose of the change

Rename Connectors guide to `Implementing out-of-the-box Connectors` to avoid confusion.

## PR Checklist

- [x] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [x] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

2022-08-29 22:23 UTC, christinaausley commented
@akeller I know https://github.com/camunda/camunda-platform-docs/pull/1205 might cause a merge conflict here but I'll resolve 👍

2022-08-30 06:35 UTC, MaxTru requested changes

2022-08-30 06:35 UTC, MaxTru commented on docs/guides/introduction-to-camunda-platform-8.md
> +- [Implement connectors](./configuring-out-of-the-box-connectors.md) - Automate complex business processes by inserting them into BPMN diagrams within Web Modeler.
Why not
```suggestion
- [Configuring an out-of-the-box connector](./configuring-out-of-the-box-connectors.md) - Automate complex business processes by inserting them into BPMN diagrams within Web Modeler.
```

2022-08-30 06:35 UTC, MaxTru commented on versioned_docs/version-8.0/guides/introduction-to-camunda-platform-8.md
> +- [Implement connectors](./configuring-out-of-the-box-connectors.md) - Automate complex business processes by inserting them into BPMN diagrams within Web Modeler.
Why not
```suggestion
- [Configuring an out-of-the-box connector](./configuring-out-of-the-box-connectors.md) - Automate complex business processes by inserting them into BPMN diagrams within Web Modeler.
```

2022-08-30 18:58 UTC, christinaausley commented on docs/guides/introduction-to-camunda-platform-8.md
> +- [Implement connectors](./configuring-out-of-the-box-connectors.md) - Automate complex business processes by inserting them into BPMN diagrams within Web Modeler.
Nice catch. Adjusting in commit.

2022-08-30 18:58 UTC, christinaausley commented on versioned_docs/version-8.0/guides/introduction-to-camunda-platform-8.md
> +- [Implement connectors](./configuring-out-of-the-box-connectors.md) - Automate complex business processes by inserting them into BPMN diagrams within Web Modeler.
Nice catch. Adjusting in commit.

2022-08-30 20:56 UTC, akeller submitted a review, later dismissed

2022-08-30 20:57 UTC, akeller commented
@christinaausley I've approved both of your Connectors PRs. Please merge them in the order you prefer 😄

2022-08-31 07:11 UTC, MaxTru approved these changes

2022-08-31 13:57 UTC, merged