docs(self-managed): restructure camunda platform 8 self-managed
camunda/camunda-platform-docs pull request #1241
Opened 2022-09-08 12:25 UTC by aabouzaid

## What is the purpose of the change

Restructure camunda platform 8 self-managed to make it easy to extend for more platforms and guides.

Related to: camunda/distribution/issues/7

## Are there related marketing activities

No.

## When should this change go live?

ASAP.

## PR Checklist

- [x] I've linted and tested the changes locally.
- [x] My changes are not for an already released version.
- [x] My changes apply to future versions, and I have added them to the main `/docs` directory.
- [x] My changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer.

2022-09-12 16:30 UTC, akeller commented
Some quick feedback - I'm surprised this didn't have issues in the link-check portion of the build process. Renaming pages will require redirects/rewrites. 

In general, I really like the new structure! @christinaausley has been on holiday, but I'll see that one of us can review this this week.

2022-09-12 16:44 UTC, aabouzaid commented
@akeller yeah I expect that too :sweat_smile: 

one thing, I've a new guide and it uses the new structure, but to make it easy for review I've opened a new PR (no. #1251).

it's up to the reviewer if I should add the guide to the current PR or just adjust the single domain guide PR after the merge.

2022-09-12 19:26 UTC, christinaausley commented
> #1251

No problem on breaking up work here into separate PRs, but if you'd rather have all the changes in one single PR, you're more than welcomed to add it to this PR. Essentially, this is up to you and your working style/preference.

I'm submitting an initial review, but let me know if you would like assistance with redirects.

2022-09-12 19:27 UTC, christinaausley requested changes
I really like this restructure. Just two comments to resolve and redirects to address, and then we should be good to go!

2022-09-12 19:27 UTC, christinaausley commented on docs/components/best-practices/architecture/deciding-about-your-stack.md
> +While there [exists a Docker Compose configuration](/docs/self-managed/platform-deployment/docker/) to run Camunda Cloud locally, this is not meant to be used for production, but rather to quickly st
This would now be Camunda Platform 8 👍

2022-09-12 19:27 UTC, christinaausley commented on docs/self-managed/platform-deployment/overview.md
> +title: "Camunda Platform installation overview"
I would adjust to Camunda Platform **8** installation overview for clarity.

2022-09-12 20:13 UTC, akeller commented
@pepopowitz is link-check passing because these changes are happening in `Next`? And not `8.0`? Or is something else going on?

2022-09-13 18:16 UTC, pepopowitz commented
> @pepopowitz is link-check passing because these changes are happening in `Next`? And not `8.0`? Or is something else going on?

Yes, that's why! The `next` docs aren't yet included in the sitemap -- [this PR puts them back in](https://github.com/camunda/camunda-platform-docs/pull/1239). Once all the optimize/v3.8.0 stuff gets merged, I'd expect those links to start failing.

2022-09-13 19:38 UTC, akeller commented
@christinaausley can you take a look at what will need redirects in this PR based on the changes in the sidebars file? Let me or @pepopowitz know if you need any help!

2022-09-14 23:15 UTC, christinaausley commented
@akeller @pepopowitz I'm really struggling with these. If you don't mind taking a look, that would be super helpful.

2022-09-15 14:54 UTC, pepopowitz commented
@christinaausley it looks like the reason the additional redirects are failing is that they're written against the "current" version of the docs (no version in the URL), but all the changes in this PR are against the "next" version (`/next/` in the URL). 

* This URL did not change in this PR, so it doesn't need a redirect: /docs/self-managed/platform-deployment/kubernetes-helm/
* A URL that _did_ change in this PR is from /docs/next/self-managed/platform-deployment/kubernetes-helm/, and it changed to /docs/next/self-managed/platform-deployment/helm-kubernetes/deployment/.

The redirects added in lines 11-16 are causing link-checking to fail, because they're redirecting to URLs that don't exist. 

---

There's one more important detail to getting this PR green -- [the release I just published to production](https://github.com/camunda/camunda-platform-docs/releases/tag/8.0.32) includes a change that adds all of the `/next/` docs back into the sitemap -- so the next time link-checking runs for this PR, I suspect we'll start to see the URLs that changed in this PR all start to fail. 

So I _think_ to get this PR green, what we need to do is add `/next/` to all of the redirect rules that you added, both on the left and right sides of each rule. 

---

There is maybe another conversation to have with @akeller about how much we care about redirects for `vNext` docs -- that version of the docs is fluid, so should we care about redirects for it? Also, there is an effect when we cut a new version -- we'll need to make sure we add _more_ redirect rules, basically the ones that you've added previously to this comment. 


That's a lot....let me know if there's anything I can clarify!

2022-09-15 18:28 UTC, akeller commented
>There is maybe another conversation to have with @akeller about how much we care about redirects for vNext docs -- that version of the docs is fluid, so should we care about redirects for it? Also, there is an effect when we cut a new version -- we'll need to make sure we add more redirect rules, basically the ones that you've added previously to this comment.

I'm good with having fluidity for vNext and not enforcing redirects. @pepopowitz what do we need to do to get this passing so we can merge without causing issues with our other PRs?

2022-09-15 19:12 UTC, pepopowitz commented
> what do we need to do to get this passing so we can merge without causing issues with our other PRs?

If we just want to get to green on this PR, we need to update the redirect rules that have been added to `.htaccess` in this PR, so that they specify the `/next/` version of those docs. 

If we want to stop worrying about redirects for `/next/` docs, we need to update our link-checking steps to ignore URLs if they match a certain pattern. I _think_ we are looking for the previous option just to get to green, and then I should add an issue for me to exclude `/next/` URLs from link-checking in a follow-up.

I can take care of adding that issue, but likely will add it tomorrow.

2022-09-15 21:57 UTC, akeller commented
I think I'm making progress. The hardest part is the link-check doesn't specify /next/ URLs but redirecting to a non-existent page (301-404) was a good hint.

2022-09-15 22:24 UTC, akeller commented
@christinaausley you were soooo so close! I added `/next/` on the left and right of all your redirects and merged in changes on `main` and finally got this working. You and @pepopowitz really did all the work here. Thank you! 🚀

2022-09-15 22:25 UTC, akeller approved these changes

2022-09-15 22:25 UTC, merged

2022-09-19 10:47 UTC, aabouzaid commented
@akeller @christinaausley @pepopowitz 
Thanks a lot for your effort :bow: