feat(rest-connector): Update docs for Rest-http Connector
camunda/camunda-platform-docs pull request #1448
Opened 2022-10-31 15:27 UTC by Oleksiivanov

## What is the purpose of the change

Update [documentation](https://docs.camunda.io/docs/next/components/integration-framework/connectors/out-of-the-box-connectors/rest/) so it reflects the new element template.

## Are there related marketing activities

https://github.com/camunda/team-connectors/issues/138

## When should this change go live?

-

## PR Checklist

- [ ] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [ ] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

2022-10-31 22:31 UTC, christinaausley submitted a review, later dismissed
Nice updates 👍  I made some minor adjustments to the connection timeout section in each of the versions in my latest commit.

2022-11-01 09:04 UTC, igpetrov commented
@MoAtCamunda could you please review this doc?

2022-11-03 16:53 UTC, MoAtCamunda requested changes

2022-11-03 16:53 UTC, MoAtCamunda commented on docs/components/connectors/out-of-the-box-connectors/rest.md
> +To make the **REST Connector** executable, choose needed authentication type and fill out the mandatory fields highlighted in red in the properties panel:
```suggestion
To make the **REST Connector** executable, choose the required authentication type and fill out the mandatory fields highlighted in red in the properties panel:
```

2022-11-07 10:16 UTC, akeller commented
This looks like it's ready to merge after incorporating @MoAtCamunda's change. @Oleksiivanov, would you agree?

2022-11-07 10:21 UTC, igpetrov commented
@akeller let's wait for some time. QAs are testing a related feature (timeout) at the moment.

2022-11-07 10:22 UTC, igpetrov approved these changes

2022-11-07 10:23 UTC, akeller commented
@igpetrov I'll add the `hold` label. Please remove it when you are ready to merge.

2022-11-07 10:29 UTC, igpetrov commented
> @igpetrov I'll add the `hold` label. Please remove it when you are ready to merge.

Perfect, thank you!

@Oleksiivanov FYI

2022-11-15 01:54 UTC, christinaausley submitted a review, later dismissed

2022-11-15 11:07 UTC, MoAtCamunda requested changes

2022-11-15 11:07 UTC, MoAtCamunda commented on docs/components/connectors/out-of-the-box-connectors/rest.md
>  ![rest Connector basic auth](../img/connectors-rest-basic-auth.png)
Should there be a secrets.YOUR_USERNAME here? if not should we use <YOUR_USERNAME>?

2022-11-16 12:57 UTC, igpetrov commented
@Oleksiivanov the `build-docs` is failing. You'll likely need to rebase.

2022-11-16 15:56 UTC, igpetrov approved these changes

2022-11-16 15:58 UTC, igpetrov commented
Hi @christinaausley,

This one is ready, can we merge it please. The related back-end code is completed and merged.

2022-11-16 16:03 UTC, merged