feat(rabbitmq-connector): add documentation for rabbitMq connector
camunda/camunda-platform-docs pull request #1449
Opened 2022-10-31 18:23 UTC by Oleksiivanov

## What is the purpose of the change

Add rabbitmq connector documentation

## Are there related marketing activities

https://github.com/camunda/connector-rabbitmq/issues/7

## When should this change go live?

15th November

## PR Checklist

- [ ] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [ ] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

2022-10-31 18:45 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +title: RabbitMq Service Connector
```suggestion
title: RabbitMQ Service Connector
```

2022-10-31 18:45 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +sidebar_label: RabbitMq Connector
```suggestion
sidebar_label: RabbitMQ Connector
```

2022-10-31 18:45 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +description: Send messages to RabbitMq from your BPMN process.
```suggestion
description: Send messages to RabbitMQ from your BPMN process.
```

2022-10-31 18:46 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +The RabbitMq Connector allows you to connect your BPMN service with [RabbitMq](https://www.rabbitmq.com/).
```suggestion
**The RabbitMQ Connector** allows you to connect your BPMN service with [RabbitMQ](https://www.rabbitmq.com/).
```

2022-10-31 18:47 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +To use the **RabbitMq Connector**, you need to have an installed RabbitMq server and credentials for use it.
```suggestion
To use the **RabbitMQ Connector**, you need to have an installed RabbitMQ server and credentials to use it.
```

2022-10-31 18:48 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +To use the **RabbitMq Connector** in your process, either change the type of existing task by clicking on it and using the wrench-shaped **Change type** context menu icon, or create a new Connector t
```suggestion
To use the **RabbitMQ Connector** in your process, either change the type of existing task by clicking on it and using the wrench-shaped **Change type** context menu icon, or create a new Connector task by using the **Append Connector** context menu. Follow our [guide on using Connectors](../use-connectors.md) to learn more.
```

2022-10-31 18:48 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +## Create an RabbitMq Connector task
```suggestion
## Create a RabbitMQ Connector task
```

2022-10-31 18:49 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +## Make your RabbitMq Connector for sending messages executable
```suggestion
## Make your RabbitMQ Connector for sending messages executable
```

2022-10-31 18:49 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +To make the **RabbitMq Connector** executable, choose needed connection type in **Authentication** section and fill out the mandatory fields highlighted in red in the properties panel:
```suggestion
To make the **RabbitMQ Connector** executable, choose needed connection type in **Authentication** section and fill out the mandatory fields highlighted in red in the properties panel:
```

2022-10-31 18:50 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +All the mandatory and non-mandatory fields will be covered in the upcoming sections. Depending on the authentication selection you make, more fields might be required. We will also cover this in the
```suggestion
All the mandatory and non-mandatory fields will be covered in the upcoming sections. Depending on the authentication selection you choose, different amount of fields are required. We will also cover this in the next section.
```

2022-10-31 18:51 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +You can choose among the available REST Connectors according to your authentication requirements.
Sorry, what REST connectors?

2022-10-31 18:52 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +First of all you need create new user in rabbitMq with needed permissions see more in [rabbitmq access control specification](https://www.rabbitmq.com/access-control.html).
```suggestion
First of all, you need have a user in your RabbitMQ instance with necessary permissions. See more at the [RabbitMQ access control specification](https://www.rabbitmq.com/access-control.html).
```

2022-10-31 18:52 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +In next step choose need type of connection:
```suggestion
In next step choose a required type of connection:
```

2022-10-31 18:53 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +2. Set **URI** to `URI`. It must contain rabbitMq username, password, host name, port number, and virtual host. Example: `amqp://userName:password@serverHost:port/virtualHost`, follow [uri rabbitmq s
```suggestion
2. Set **URI** to `URI`. It must contain RabbitMQ username, password, host name, port number, and virtual host. Example: `amqp://userName:password@serverHost:port/virtualHost`, follow the [RabbitMQ URI specification](https://www.rabbitmq.com/uri-spec.html) to learn more.
```

2022-10-31 18:54 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +  "port": "your-rabbitmq-port-number"
```suggestion
{
  "exchange": "<your-rabbitmq-exchange-name>",
  "routingKey": "<your-rabbitmq-routing-key-name>",
  "virtualHost": "<your-rabbitmq-virtual-host-name>",
  "hostName": "<your-rabbitmq-host-name-or-ip-address>",
  "port": "<your-rabbitmq-port-number>"
```

2022-10-31 18:55 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +For **URI** type connection required fields : `exchange` and `exchangeDemo`.
What is `exchangeDemo`?

2022-10-31 18:56 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +1. Set your message payload to **Message** section. Message can be text and json format.
```suggestion
1. Set your message payload to **Message** section. Message can be text and JSON format.
```

2022-10-31 18:56 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +2. (Optional) Set message properties (json format or FEEL expression format) to **Properties** section. Follow [rabbitmq documentation](https://www.rabbitmq.com/publishers.html#message-properties) fo
```suggestion
2. (Optional) Set message properties (JSON format or FEEL expression format) to **Properties** section. Follow [RabbitMQ documentation](https://www.rabbitmq.com/publishers.html#message-properties) for learn more about message properties.
```

2022-10-31 18:57 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +## RabbitMq Connector response
```suggestion
## RabbitMQ Connector response
```

2022-10-31 18:57 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +The **RabbitMq Connector** returns the Success result.
```suggestion
The **RabbitMQ Connector** returns the `Success` result.
```

2022-11-01 09:24 UTC, igpetrov commented
@MoAtCamunda this is RabbitMQ documentation

2022-11-01 20:31 UTC, christinaausley approved these changes
A few non-blocking comments for clarification and technical adjustments in my latest commit if you'd like to take a closer look. Is there a reason why this PR is still a draft? Are you planning on adding changes, or can this be moved out of draft?

2022-11-01 20:31 UTC, christinaausley commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +For a **Credentials** type connection, all fields are required.
To confirm, filling out all of the fields is required here?

2022-11-01 20:31 UTC, christinaausley commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +1. Set your message payload to **Message** section. Message can be text and JSON format.
What do you mean here? Do you mean, "In the **Message** section, insert the message payload."?

2022-11-01 20:31 UTC, christinaausley commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +2. (Optional) Set message properties (JSON format or FEEL expression format) to **Properties** section. Follow [RabbitMQ documentation](https://www.rabbitmq.com/publishers.html#message-properties) fo
Similar comment here. Do you mean "In the **Properties** section, insert the message properties in JSON or FEEL expression format."?

2022-11-01 22:45 UTC, christinaausley commented
@Oleksiivanov No problem, just wanted to double check I reviewed all of your planned changes. If you're more comfortable keeping this as a draft until you're ready for prod, feel free to do so 👍

2022-11-01 22:47 UTC, christinaausley commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +For a **Credentials** type connection, all fields are required.
Added in my latest commit 👍

2022-11-01 22:48 UTC, christinaausley commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +1. Set your message payload to **Message** section. Message can be text and JSON format.
Added in my latest commit.

2022-11-01 22:48 UTC, christinaausley commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +2. (Optional) Set message properties (JSON format or FEEL expression format) to **Properties** section. Follow [RabbitMQ documentation](https://www.rabbitmq.com/publishers.html#message-properties) fo
Added in my latest commit.

2022-11-02 09:10 UTC, igpetrov commented
@MoAtCamunda could you please take a look at it?

2022-11-03 16:50 UTC, MoAtCamunda requested changes

2022-11-03 16:50 UTC, MoAtCamunda commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +To use the **RabbitMQ Connector**, you need to have an installed RabbitMQ server and credentials to use it.
```suggestion
To use the **RabbitMQ Connector**, you need to have an installed RabbitMQ server and relevant credentials.
```

2022-11-03 16:50 UTC, MoAtCamunda commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +Ensure you write out the correct exchange name and routing key, because the **RabbitMQ Connector** can't throw an exception if they are incorrect.
```suggestion
Ensure you write out the correct exchange name and routing key, as the **RabbitMQ Connector** can't throw an exception if they are incorrect.
```

2022-11-03 16:50 UTC, MoAtCamunda commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +To make the **RabbitMQ Connector** executable, choose the needed connection type in the **Authentication** section and fill out the mandatory fields highlighted in red in the properties panel:
```suggestion
To connect to RabbitMQ, choose the required connection type in the **Authentication** section and complete the mandatory fields highlighted in red in the properties panel:
```

2022-11-03 16:50 UTC, MoAtCamunda commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +## Make your RabbitMQ Connector for sending messages executable
```suggestion
## Connecting to RabbitMQ and sending messages
```

2022-11-03 16:50 UTC, MoAtCamunda commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +For a credentials connection, take the following steps:
```suggestion
To connect with credentials, take the following steps:
```

2022-11-03 16:50 UTC, MoAtCamunda commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +In the **Routing** section you must set routing data (free feel use JSON format and FEEL expression format):
```suggestion
In the **Routing** section you must set the routing data attributes (you can either use JSON or a FEEL expression):
```

2022-11-03 16:50 UTC, MoAtCamunda commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +```
Can we add a FEEL expression example here?

2022-11-03 16:50 UTC, MoAtCamunda commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +2. (Optional) In the **Properties** section, insert the message properties in JSON or FEEL expression format. Follow [RabbitMQ documentation](https://www.rabbitmq.com/publishers.html#message-properti
```suggestion
2. (Optional) In the **Properties** section, insert the message properties in JSON or as a FEEL expression. Follow [RabbitMQ documentation](https://www.rabbitmq.com/publishers.html#message-properties) for learn more about message properties.
```

2022-11-03 18:41 UTC, MoAtCamunda commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +```
excellent! thanks

2022-11-03 18:42 UTC, MoAtCamunda approved these changes

2022-11-04 17:54 UTC, christinaausley approved these changes

2022-11-08 10:09 UTC, MoAtCamunda requested changes
added a few minor adjustments

2022-11-08 10:09 UTC, MoAtCamunda commented on versioned_docs/version-8.0/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +Ensure you write out the correct exchange name and routing key, as the **RabbitMQ Connector** can't throw an exception if they are incorrect.
```suggestion
Make sure the exchange name and routing key is correct, as the **RabbitMQ Connector** can't throw an exception if they are invalid.
```

2022-11-08 10:09 UTC, MoAtCamunda commented on versioned_docs/version-8.0/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +To use the **RabbitMQ Connector** in your process, either change the type of existing task by clicking on it and using the wrench-shaped **Change type** context menu icon, or create a new Connector t
```suggestion
To use the **RabbitMQ Connector** in your process, either change the type of the existing task by clicking on it and using the wrench-shaped **Change type** context menu icon, or create a new Connector task by using the **Append Connector** context menu. Follow our [guide to using Connectors](../use-connectors.md) to learn more.
```

2022-11-08 10:09 UTC, MoAtCamunda commented on versioned_docs/version-8.0/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +2. Set **URI** to `URI`. It must contain RabbitMQ username, password, host name, port number, and virtual host. For example, `amqp://userName:password@serverHost:port/virtualHost`; follow the [Rabbit
```suggestion
2. Set **URI** to `URI`. It must contain the RabbitMQ username, password, host name, port number, and virtual host. For example, `amqp://userName:password@serverHost:port/virtualHost`; follow the [RabbitMQ URI specification](https://www.rabbitmq.com/uri-spec.html) to learn more.
```

2022-11-10 16:56 UTC, igpetrov submitted a review, later dismissed

2022-11-15 11:07 UTC, MoAtCamunda requested changes

2022-11-15 11:07 UTC, MoAtCamunda commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +2. Use **Result Expression** to map fields from the response into process variables. For example:
```suggestion
2. Use **Result Expression** to map specific fields from the response into process variables using [FEEL](https://docs.camunda.io/docs/components/modeler/feel/what-is-feel/). For example:
```

2022-11-16 14:33 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +To use the **RabbitMQ Connector** in your process, either change the type of existing task by clicking on it and using the wrench-shaped **Change type** context menu icon, or create a new Connector t
@Oleksiivanov can you please create a follow up ticket to add icons as a separate task?

2022-11-16 14:35 UTC, igpetrov approved these changes

2022-11-16 15:52 UTC, igpetrov submitted a review, later dismissed
LGTM. Re-approving after changes.

2022-11-16 16:32 UTC, MoAtCamunda approved these changes

2022-11-16 16:35 UTC, mbiciin commented on versioned_docs/version-8.0/components/connectors/out-of-the-box-connectors/rabbitmq.md
> +You can choose among the available RabbitMQ Connectors according to your authentication requirements.
Are you referring here to the different authentication types? If that's the case, I would suggest something like:
"You can choose from the available authentication types of the RabbitMQ Connector depending on your authentication requirements."

2022-11-16 16:36 UTC, mbiciin reviewed
Looks very good. :)

2022-11-16 16:51 UTC, igpetrov approved these changes

2022-11-16 16:52 UTC, merged