Rectify information on EBS-CSI driver
camunda/camunda-platform-docs pull request #1559
Opened 2022-12-06 04:43 UTC by jothikiruthika-camunda

Our docs mentions - If you are already on 1.23 or later, the driver is already installed. But, as per the official EKS documentation, the add-on is not installed automatically. But , Refer EKS docs, "The Amazon EBS CSI driver isn't installed when you first create a cluster. To use the driver, you must add it as an Amazon EKS add-on or as a self-managed add-on." - https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html "If you plan to deploy workloads that use Amazon EBS volumes in a new 1.23 cluster, install the Amazon EBS CSI driver in your cluster before deploying the workloads your cluster. "- https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.23 I have just installed C8 using helm profiles on a 1.23 Version EKS cluster and I had to add it manually.

## What is the purpose of the change

_Briefly describe the change you are making, this helps the reviewer by providing an overview._

## Are there related marketing activities

_Are there any marketing activities related to the related feature or component? If so, please briefly describe them._

## When should this change go live?

_Does this change need to be released before a certain date or milestone? If so, when?_

## PR Checklist

- [ ] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [ ] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

2022-12-06 22:23 UTC, akeller requested changes
Can you add these changes to `/docs/` too please so they are on future versions moving forward?

2022-12-07 15:43 UTC, aabouzaid approved these changes
LGTM, thanks for improving the docs :+1:

2022-12-07 23:57 UTC, christinaausley approved these changes
Approving from a technical perspective, but do see @akeller's comment before merging 👍

2022-12-08 01:44 UTC, jothikiruthika-camunda commented
> Can you add these changes to `/docs/` too please so they are on future versions moving forward?

Hi @akeller, changes made in docs as well. You can now review and merge.

2022-12-08 15:35 UTC, akeller approved these changes

2022-12-08 15:35 UTC, merged