docs(ootb connectors): document inbound connector
camunda/camunda-platform-docs pull request #1593
Opened 2022-12-26 13:35 UTC by igpetrov

## What is the purpose of the change

Document inbound connector capabilities.

## Are there related marketing activities

TBD

## When should this change go live?

_Does this change need to be released before a certain date or milestone? If so, when?_

## PR Checklist

- [ ] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [ ] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

2022-12-28 12:50 UTC, christinaausley commented
Happy to provide a technical review here as well when you're ready.

2023-01-10 14:00 UTC, markfarkas-camunda requested changes
Looks good, there are just a few typo.

2023-01-10 14:00 UTC, markfarkas-camunda commented on docs/components/connectors/out-of-the-box-connectors/http-webhook.md
> +3. Feel in all required properties.
Typo: 'Feel in' should be 'Fill in'

2023-01-10 14:00 UTC, markfarkas-camunda commented on docs/components/connectors/use-connectors.md
> +3. Feel in all required properties.
Typo: 'Feel in' should be 'Fill in'

2023-01-10 14:00 UTC, markfarkas-camunda commented on docs/components/connectors/use-connectors.md
> +In order to be able to deploy and use inbound webhook, you would need to feel in several fields.
Typo: 'Feel in' should be 'Fill in'

2023-01-11 10:02 UTC, mbiciin commented on docs/components/connectors/out-of-the-box-connectors/github-webhook.md
> +4. Configure **Variable Mapping**. For example, given GitHub triggers a webhook endpoint with a new PR payload `{"action": "opened", "pull_request": { "url: "https://...", ... }}` and you would like
```suggestion
4. Configure **Variable Mapping**. For example, given that GitHub triggers a webhook endpoint with a new PR payload `{"action": "opened", "pull_request": { "url: "https://...", ... }}` and you would like to extract a PR URL as a process variable `prUrl`, the **Variable Mapping** might look as `={prUrl: request.body.pull_request.url}`.

```
or 
```suggestion
4. Configure **Variable Mapping**. For example, GitHub triggers a webhook endpoint with a new PR payload `{"action": "opened", "pull_request": { "url: "https://...", ... }}` and you would like to extract a PR URL as a process variable `prUrl`. In that case, the **Variable Mapping** might look as `={prUrl: request.body.pull_request.url}`.

2023-01-11 10:02 UTC, mbiciin requested changes
Looks good to me. :). I have few minor suggestions. I added them in the comments. I would also suggest changing the screenshots docs/components/connectors/img/use-inbound-connector-template-filled.png and docs/components/connectors/img/use-inbound-connector-template.png to be consistent with these changes https://github.com/camunda/web-modeler/pull/3498/files concerning the description for condition and variables.

2023-01-11 10:59 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/github-webhook.md
> +3. Feel in all required properties.
```suggestion
3. Fill in all required properties.
```

2023-01-11 10:59 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/http-webhook.md
> +3. Feel in all required properties.
```suggestion
3. Fill in all required properties.
```

2023-01-11 11:00 UTC, igpetrov commented on docs/components/connectors/use-connectors.md
> +3. Feel in all required properties.
```suggestion
3. Fill in all required properties.
```

2023-01-11 11:00 UTC, igpetrov commented on docs/components/connectors/use-connectors.md
> +In order to be able to deploy and use inbound webhook, you would need to feel in several fields.
```suggestion
In order to be able to deploy and use inbound webhook, you would need to fill in several fields.
```

2023-01-11 14:08 UTC, berndruecker commented
I would look at this now. @igpetrov Can I do some changes and push it to this branch? I basically ask to avoid merge conflicts as much as possible :-) 
As I can imagine I might do some bigger additions - I could also do it after this PR is merged if you prefer?

2023-01-11 14:10 UTC, igpetrov commented
Hi @berndruecker,

Please make changes on this branch. There's nothing currently pending from my side.

2023-01-11 14:44 UTC, berndruecker commented
Done

2023-01-11 15:58 UTC, igpetrov commented
Thanks @berndruecker for taking care of it.

I just wanted to give https://github.com/camunda-cloud/identity/issues/1439 a try and make it working otherwise we should cover creating permissions in docs somewhere.

I am taking care of it here https://github.com/camunda/camunda-platform/issues/77. Probably should come up with a resolution tomorrow.

2023-01-12 17:43 UTC, igpetrov commented
Good day, @christinaausley.

This one is ready for review & merge.

Thank you!

2023-01-17 22:41 UTC, christinaausley approved these changes
Technical review in latest commit for styling and grammatical adjustments -- let me know if you have any questions about these!

2023-01-17 23:24 UTC, merged