docs: updating screenshots for tasklist 8.2
camunda/camunda-platform-docs pull request #1872
Opened 2023-03-29 18:04 UTC by marcosgvieira

## What is the purpose of the change

_Briefly describe the change you are making, this helps the reviewer by providing an overview._

As we added more fields in tasklist, updating screenshots and adding descriptions on what have changed

## Are there related marketing activities

_Are there any marketing activities related to the related feature or component? If so, please briefly describe them._

## When should this change go live?

_Does this change need to be released before a certain date or milestone? If so, when?_

## PR Checklist

- [ ] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [ ] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

2023-03-30 08:41 UTC, vsgoulart requested changes

2023-03-30 08:41 UTC, vsgoulart commented on docs/components/tasklist/userguide/using-tasklist.md
> +> **_NOTE:_** This tab is only available for Self-Managed environments at the moment
```suggestion
> **_NOTE:_** This tab is only available for Self-Managed environments or an alpha cluster at Camunda Platform  at the moment
```

2023-03-30 22:40 UTC, christinaausley approved these changes
Technical review in latest commit 👍

2023-03-31 09:21 UTC, christian-konrad requested changes
I requested quite some changes in the text. I left comments for proposals to update the paragraphs.

Please also update the title of the PR since it also covers text changes, not just screenshot changes.

2023-03-31 09:21 UTC, christian-konrad commented on docs/components/tasklist/userguide/using-tasklist.md
> +You can also order the tasks on the left menu, clicking on the icon ![order-icon](img/order-icon.png):
Rephrase to

"Click on the icon ![order-icon](img/order-icon.png) to order the tasks. You can order them by the date of creation, the due date, or the follow up date.

The follow up date defines the latest time you should start working on a task, helping you to prioritize work.
The due date provides a deadline when the task should be finished."

2023-03-31 09:21 UTC, christian-konrad commented on docs/components/tasklist/userguide/using-tasklist.md
>  You can choose which tasks you want to see:
Rephrase to 

"Click on the selection field in the left panel to choose which tasks you want to see."

2023-03-31 09:21 UTC, christian-konrad commented on docs/components/tasklist/userguide/using-tasklist.md
> +Initially, we have no **Assigned to me** tasks.
Rephrase to "When no tasks are assigned to you, the list appears empty."

2023-03-31 09:21 UTC, christian-konrad commented on docs/components/tasklist/userguide/using-tasklist.md
> +Select the **Unassigned** list and assign a task using the **Assign to me** button on the top panel:
Rephrase to "Select the **Unassigned** list and assign a task to yourself using the **Assign to me** button on the top panel."

2023-03-31 09:21 UTC, christian-konrad commented on docs/components/tasklist/userguide/using-tasklist.md
> +### Assigned to me tasks
Rephrase to "Work on assigned tasks"

2023-03-31 09:21 UTC, christian-konrad commented on docs/components/tasklist/userguide/using-tasklist.md
> +Select the **Assigned to me** list to see if you assigned the task:
Rephrase to "Select the **Assigned to me** list to see the tasks that are assigned to you. Select a task to work on it."

2023-03-31 09:21 UTC, christian-konrad commented on docs/components/tasklist/userguide/using-tasklist.md
> +Once you are assigned a task, you can complete the task by adding and updating variables, and using the **Complete Task** button:
Rephrase to "When a task is assigned to you, you can complete the task by filling out the given form, and clicking on the **Complete Task** button. There are also cases where no form is available. In these cases, you have to add and/or update variables directly."

2023-03-31 10:23 UTC, marcosgvieira commented
@christian-konrad can you please review again?

2023-04-03 09:21 UTC, vsgoulart approved these changes

2023-04-03 18:03 UTC, christinaausley approved these changes

2023-04-03 18:46 UTC, merged