reorder APIs in sidebar
camunda/camunda-platform-docs pull request #1966
Opened 2023-04-13 17:59 UTC by christinaausley

## What is the purpose of the change

Closes https://github.com/camunda/camunda-platform-docs/issues/1960.

How do we feel about this ordering? Currently, it is based on the card layout, so if we want to adjust, I'll need to adjust on that end as well 👍 

## PR Checklist

- [x] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [x] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

2023-04-13 21:45 UTC, akeller submitted a review, later dismissed
No strong opinions from me here, just interested in consistency.

I could make a case for alphabetical order, potential interest/use, or order in which you may encounter them when working with C8.

Let's see if anyone has any feedback on this ordering. We can always change it 🙂

2023-04-13 21:46 UTC, akeller commented
It says there are no conflicts here, but I didn't see the two Tasklist cards, so you may want to update the branch and confirm that looks how you want it to.

2023-04-17 15:57 UTC, pepopowitz requested changes
Blocking: my request for synchronizing the sidebars.

Non-blocking: While prepping for the release I remember being baffled by the order of these links. I wished they were in alphabetical, because I couldn't think of any logical ordering that would be consistent for everyone. I prefer alphabetic order, because I can't associate with any logical ordering that is present in these changes, either.

2023-04-17 15:57 UTC, pepopowitz commented on sidebars.js
I think we would need to make parallel changes to the optimize-3.10.0-sidebars.json. Since this is a pretty significant change, I think we should synchronize here in this PR, instead of waiting to synchronize before the next release.

2023-04-17 19:11 UTC, christinaausley commented on sidebars.js
@pepopowitz Would you prefer I pop some time on your calendar, or go ahead and make these changes in this PR for your review?

2023-04-17 19:59 UTC, pepopowitz commented on sidebars.js
In this PR works for me! If you want to pair on it, we can, but if you're comfortable making the changes I say go for it.

2023-04-18 18:59 UTC, christinaausley commented
@akeller @pepopowitz Alphabetized sidebars here -- need a second set of eyes as I've been staring at so many curly brackets for too long.

2023-04-18 19:40 UTC, akeller requested changes
Public API isn't actually an API, but more like an overview page. I'm bringing this topic back to the C8 Stakeholder meeting so we can either remove it or update it, but it should be at the top, with the actual APIs in alphabetical order to follow. 

Let me see if I can fix it for you, for the sake of your eyeballs 👁️ 👁️

2023-04-18 20:18 UTC, pepopowitz approved these changes
This is very satisfying, thank you!

2023-04-19 14:56 UTC, merged