docs(identity): add logging configuration page detailing options available
camunda/camunda-platform-docs pull request #2061
Opened 2023-05-03 12:14 UTC by Ben-Sheppard

Closes https://github.com/camunda-cloud/identity/issues/1740

## What is the purpose of the change
There have been recent requests from clients based on the Identity logging configuration that could have been solved by better documentation around the options available.

This PR introduces a dedicated page detailing the options for logging in Identity, including:
* The framework used
* The supplied configuration options
* A method for supplying your own logging configuration

## Are there related marketing activities
There are not :)

## When should this change go live?
This change is not part of a wider co-ordinated effort and I would not consider it urgent, therefore it is fine to be released in the natural release cadence.

## PR Checklist

- [x] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [x] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

2023-05-03 15:44 UTC, dlavrenuek requested changes
Great addition 🏅 Some small suggestions from my side

2023-05-03 15:44 UTC, dlavrenuek commented on docs/self-managed/identity/user-guide/configuration/configure-logging.md
> +<?xml version="1.0" encoding="UTF-8"?>
The included configuration file here is missing any description. We should add something like "following is the log4j configuration included in Identity".

2023-05-03 15:44 UTC, dlavrenuek commented on docs/self-managed/identity/user-guide/configuration/configure-logging.md
> +The default logging configuration file can be overridden by setting the following variable:
This sentence just tells the user to set the `LOGGING_CONFIG`, which does not answer following questions that users will probably have:
- where is my logging configuration?
- how do I add my logging configuration to Identity?
- are there any rules for file location?

May be something like?

```
You can provide your own configuration by mounting the configuration file to the Identity container and setting it's path in the following variable:
```

2023-05-03 15:44 UTC, dlavrenuek commented on versioned_docs/version-8.1/self-managed/identity/user-guide/configure-logging.md
> +        </RollingFile>
@Ben-Sheppard if this is referenced as what we include per default, then `File` logger is not included on 8.1

2023-05-04 15:22 UTC, dlavrenuek approved these changes
@christinaausley I have fixed some small errors in the last commit and it looks from my perspective

2023-05-04 17:05 UTC, christinaausley commented
> @christinaausley I have fixed some small errors in the last commit and it looks from my perspective

Awesome. I'll merge and launch this with the release today. We can always iterate moving forward 👍

2023-05-04 17:05 UTC, merged