Add a hint on how to create a multi-instance from a range
camunda/camunda-platform-docs pull request #2213
Opened 2023-06-12 12:07 UTC by jonathanlukas

## Description

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [x] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [ ] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

Originates from https://camunda.slack.com/archives/C01QYD808A3/p1686567499489459

Tagging @saig0

2023-06-13 09:22 UTC, saig0 reviewed
@jonathanlukas thank you for this addition. :tada: 

Please have a look at my suggestion. If you don't like it, we can go with the original change. :+1:

2023-06-13 09:22 UTC, saig0 commented on docs/components/modeler/bpmn/multi-instance/multi-instance.md
> +
@jonathanlukas what do you think about the following suggestion?
- wrapping the tip into an Admonitions tip box
- linking to the FEEL docs

```suggestion
:::tip

If you need to iterate `n` times (like with a loop-cardinality), you can use the following expression with a [for-loop](/components/modeler/feel/language-guide/feel-control-flow.md#for-loops): `for i in 1..n return i`.

:::
```

2023-06-16 04:39 UTC, jonathanlukas commented
Thank you @saig0 , this is very much appreciated. Much better than my suggestion actually.

2023-06-16 05:09 UTC, saig0 requested changes
@jonathanlukas please apply the suggestion also to docs for version `8.2`. This version is still not changed. :sweat_smile:

2023-06-26 08:10 UTC, saig0 approved these changes
@jonathanlukas LGTM. :+1:

2023-06-26 12:49 UTC, merged