Documents: Fix brockers status checks #2207
camunda/camunda-platform-docs pull request #2266
Opened 2023-06-27 12:02 UTC by rodrigo-lourenco-lopes

## Description

In this [PR](https://github.com/camunda/camunda-platform-docs/pull/2207) removed the broker status endpoint documentation, when in fact these still exist.

The configuration values were corrected with the correct configuration name.

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [ ] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

2023-06-27 16:13 UTC, akeller reviewed
Are these endpoints correct? Based on the conversation in the other PR it sounds like this is available in both SaaS and SM.

2023-06-28 09:40 UTC, rodrigo-lourenco-lopes commented
@akeller That is a good point. I replace `server.port` with zeebe-broker to be more generic since it can be either `server.port` or `server.host`, and also changed the sentence at the end on how to configure them both.
wdyt?

2023-06-28 20:17 UTC, rodrigo-lourenco-lopes commented
While testing the configurability of the server.host, we noticed that this configuration name had been replaced by server.address. An [issue](https://github.com/camunda/camunda-platform-docs/issues/2273) was opened and changes to the update-guide were added in order to reflect this.

2023-07-03 06:33 UTC, megglos requested changes
As the port is not a default http port let's add it to the endpoint url listed. To simplify we can also just set it to 9600 and rather hint on how to configure it separately, wdyt?

2023-07-03 06:33 UTC, megglos commented on versioned_docs/version-8.0/self-managed/zeebe-deployment/operations/health.md
> +Startup check endpoint is exposed via `http://{zeebe-broker}/startup` (by default port 9600).
```suggestion
Startup check endpoint is exposed via `http://{zeebe-broker-host}:9600/startup`.
The server port is configurable via spring's [server.port](https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.server.server.port) property.
```

2023-07-03 06:33 UTC, megglos commented on versioned_docs/version-8.1/self-managed/zeebe-deployment/operations/health.md
> +Startup check endpoint is exposed via `http://{zeebe-broker}/startup` (by default port 9600).
```suggestion
Startup check endpoint is exposed via `http://{zeebe-broker-host}:9600/startup`.
The server port is configurable via spring's [server.port](https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.server.server.port) property.
```

2023-07-03 06:33 UTC, megglos commented on versioned_docs/version-8.2/self-managed/zeebe-deployment/operations/health.md
> +Startup check endpoint is exposed via `http://{zeebe-broker}/startup` (by default port 9600).
```suggestion
Startup check endpoint is exposed via `http://{zeebe-broker-host}:9600/startup`.
The server port is configurable via spring's [server.port](https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.server.server.port) property.
```

2023-07-03 07:26 UTC, rodrigo-lourenco-lopes commented on docs/self-managed/zeebe-deployment/operations/health.md
> +Startup check endpoint is exposed via `http://{zeebe-broker}/startup` (by default port 9600).
We already have this hint:

`(The default broker port can be configured using environment variables - respectively `SERVER_PORT` and `SERVER_ADDRESS` - or system properties - respectively `-Dserver.port=` or `-Dserver.address=` - to configure them)`

Should we add something else?

2023-07-03 10:07 UTC, megglos commented on docs/self-managed/zeebe-deployment/operations/health.md
> +Startup check endpoint is exposed via `http://{zeebe-broker}/startup` (by default port 9600).
We can also reuse that here 👍

2023-07-03 11:11 UTC, megglos approved these changes
👍

2023-07-03 11:11 UTC, megglos commented
> Are these endpoints correct? Based on the conversation in the other PR it sounds like this is available in both SaaS and SM.

These are actually only relevant for SM, as in SaaS there is no direct access to the broker.

2023-07-03 11:15 UTC, rodrigo-lourenco-lopes commented
bors merge

2023-07-03 11:17 UTC, megglos commented
> bors merge

no bors here :D Let's also give @akeller the chance to double-check

2023-07-03 21:21 UTC, akeller approved these changes
Great catch on the address pieces @rodrigo-lourenco-lopes! So subtle, but will definitely make users 🤪 .

Thanks for your patience 😄 I will approve and merge this! 🚀

2023-07-03 21:21 UTC, merged